#!/bin/bash
#=======================
# Author : Ali Moradzade
# Created: 2022/01/09
#=======================

# use this script to convert netbeans project into eclipse project. (.project, .classpath and .settings files are taken from eclipse project)

echo "Processing projects started ..."
for f in *
do
	if [ -d "$f" ]
	then
		cd "$f"
		mkdir bin/
		cp ../.classpath .
		cp -r ../.settings .
		sed "3c\\\t<name>$(basename $f)</name>" ../.project > .project
		cd ..
	fi
done
echo "Process finished successfully."
